---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
  match: "**/*"
- type: directory
  path: content/performances
  label: Performances
  create: documents
  match: "**/*"
  templates:
  - performance
- type: directory
  path: content/photos
  label: Gallery
  create: documents
  match: "**/*"
  templates:
  - gallery-photo
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.52'
