---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home Page
- type: directory
  path: content/performances
  label: Performances
  create: documents
  match: "**/*"
  templates:
  - performance
- type: directory
  path: content/photos
  label: Gallery
  create: documents
  match: "**/*"
  templates:
  - gallery-photo
- type: document
  path: content/ringers.md
  label: Ringers Page
- type: document
  path: content/audition.md
  label: Autitions Page
- type: document
  path: content/donors.md
  label: Donors Page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.52
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.52
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.52'
